# site settings
title: Aron Nisbel
subtitle:
email: aron.nisbel@hotmail.com
description: I'm a Master of Science student in Interaction Technology & Design at Ume책 University and here is my Portfolio of projects I've made and been part of.
baseurl: "/Aron-Nisbel" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Mariehemsv채gen 27A
city: Ume책
state: V채sterbotten
zip_code: 90652
country: Sweden
phone: +46 73 821 32 22

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/HeavyKladdkaka
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/aronnisbel/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
